In [5]:
import kagglehub
import shutil
import os
import pandas as pd
import warnings 
warnings.filterwarnings("ignore")

# Define the desired download location
custom_path = "D:\SAMITH\Tableau-Projects\Logistics and Supply Chain Dashboard"

# Download the dataset (this will be stored in the default cache location)
path = kagglehub.dataset_download("datasetengineer/logistics-and-supply-chain-dataset")

# Find the versioned folder inside the downloaded dataset
versioned_folder = os.path.join(path, "versions")
if os.path.exists(versioned_folder):
    subfolders = os.listdir(versioned_folder)
    if subfolders:
        dataset_path = os.path.join(versioned_folder, subfolders[0])  # Get the first version folder
    else:
        dataset_path = path
else:
    dataset_path = path

# Ensure the destination directory exists
os.makedirs(custom_path, exist_ok=True)

# Move dataset contents instead of the whole "1" folder
for item in os.listdir(dataset_path):
    shutil.move(os.path.join(dataset_path, item), custom_path)

print("Dataset moved to:", custom_path)

Dataset moved to: D:\SAMITH\Tableau-Projects\Logistics and Supply Chain Dashboard

In [6]:
logistics_supply_chain = pd.read_csv("dynamic_supply_chain_logistics_dataset.csv")

In [8]:
logistics_supply_chain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32065 entries, 0 to 32064
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   timestamp                        32065 non-null  object
 1   vehicle_gps_latitude             32065 non-null  float64
 2   vehicle_gps_longitude            32065 non-null  float64
 3   fuel_consumption_rate            32065 non-null  float64
 4   eta_variation_hours              32065 non-null  float64
 5   traffic_congestion_level         32065 non-null  float64
 6   warehouse_inventory_level        32065 non-null  float64
 7   loading_unloading_time           32065 non-null  float64
 8   handling_equipment_availability  32065 non-null  float64
 9   order_fulfillment_status         32065 non-null  float64
 10  weather_condition_severity       32065 non-null  float64
 11  port_congestion_level            32065 non-null  float64
 12  shipping_costs                   32065 non-null  float64
 13  supplier_reliability_score       32065 non-null  float64
 14  lead_time_days                   32065 non-null  float64
 15  historical_demand                32065 non-null  float64
 16  iot_temperature                  32065 non-null  float64
 17  cargo_condition_status           32065 non-null  float64
 18  route_risk_level                 32065 non-null  float64
 19  customs_clearance_time           32065 non-null  float64
 20  driver_behavior_score            32065 non-null  float64
 21  fatigue_monitoring_score         32065 non-null  float64
 22  disruption_likelihood_score      32065 non-null  float64
 23  delay_probability                32065 non-null  float64
 24  risk_classification              32065 non-null  object
 25  delivery_time_deviation          32065 non-null  float64
dtypes: float64(24), object(2)
memory usage: 6.4+ MB

In [9]:
logistics_supply_chain.shape

(32065, 26)

In [10]:
logistics_supply_chain

,timestamp,vehicle_gps_latitude,vehicle_gps_longitude,fuel_consumption_rate,eta_variation_hours,traffic_congestion_level,warehouse_inventory_level,loading_unloading_time,handling_equipment_availability,order_fulfillment_status,...,iot_temperature,cargo_condition_status,route_risk_level,customs_clearance_time,driver_behavior_score,fatigue_monitoring_score,disruption_likelihood_score,delay_probability,risk_classification,delivery_time_deviation
0,2021-01-01 00:00:00,40.375568,-77.014318,5.136512,4.998009,5.927586,985.716862,4.951392,0.481294,0.761166,...,0.574400,0.777263,1.182116,0.502006,0.033843,0.978599,0.506152,0.885291,Moderate Risk,9.110682
1,2021-01-01 01:00:00,33.507818,-117.036902,5.101512,0.984929,1.591992,396.700206,1.030379,0.620780,0.196594,...,-9.753493,0.091839,9.611988,0.966774,0.201725,0.918586,0.980784,0.544178,High Risk,8.175281
2,2021-01-01 02:00:00,30.020640,-75.269224,5.090803,4.972665,8.787765,832.408935,4.220229,0.810933,0.152742,...,-6.491034,0.253529,6.570431,0.945627,0.264045,0.394215,0.998633,0.803322,High Risk,1.283594
3,2021-01-01 03:00:00,36.649223,-70.190529,8.219558,3.095064,0.045257,0.573283,0.530186,0.008525,0.811885,...,-0.151276,0.877576,0.548952,4.674035,0.362885,0.905444,0.993320,0.025977,High Risk,9.304897
4,2021-01-01 04:00:00,30.001279,-70.012195,5.000075,3.216077,8.004851,914.925067,3.620890,0.020083,0.053659,...,2.429448,0.262081,8.861443,3.445429,0.016957,0.258702,0.912433,0.991122,High Risk,7.752484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32060,2024-08-28 20:00:00,48.496665,-104.031158,5.421806,4.394370,0.192421,127.684977,3.607803,0.208643,0.992997,...,-8.835069,0.199377,9.893402,0.966050,0.109571,0.511074,0.953467,0.916745,High Risk,5.506049
32061,2024-08-28 21:00:00,34.670137,-89.893091,10.624778,2.700635,8.736143,84.638889,1.218165,0.472389,0.946031,...,-2.517654,0.673775,0.854378,1.665889,0.530289,0.868418,0.995329,0.808963,High Risk,-1.876938
32062,2024-08-28 22:00:00,42.963338,-82.149873,5.071596,0.485288,7.420200,48.500920,4.999149,0.064366,0.437687,...,29.410878,0.949644,4.480552,0.690990,0.537100,0.896798,0.442299,0.959197,Moderate Risk,9.790219
32063,2024-08-28 23:00:00,32.082410,-70.070154,5.000000,4.759411,0.932050,972.437425,0.505242,0.250949,0.517051,...,-6.951137,0.407377,9.185549,4.462204,0.012896,0.463018,0.999999,0.557340,High Risk,9.956879
32064,2024-08-29 00:00:00,38.576482,-94.579542,5.000046,4.068440,7.156608,16.669708,2.207746,0.486014,0.985761,...,18.796515,0.876529,2.112655,2.118384,0.974045,0.759489,0.996928,0.999230,High Risk,2.099656

In [12]:
logistics_supply_chain.columns.unique()

Index(['timestamp', 'vehicle_gps_latitude', 'vehicle_gps_longitude',
       'fuel_consumption_rate', 'eta_variation_hours',
       'traffic_congestion_level', 'warehouse_inventory_level',
       'loading_unloading_time', 'handling_equipment_availability',
       'order_fulfillment_status', 'weather_condition_severity',
       'port_congestion_level', 'shipping_costs', 'supplier_reliability_score',
       'lead_time_days', 'historical_demand', 'iot_temperature',
       'cargo_condition_status', 'route_risk_level', 'customs_clearance_time',
       'driver_behavior_score', 'fatigue_monitoring_score',
       'disruption_likelihood_score', 'delay_probability',
       'risk_classification', 'delivery_time_deviation'],
      dtype='object')

In [13]:
# specifying the column names that I want to use
new_cols_dict ={
    'timestamp':'time'
}

# Renaming the columns to the specified column names
logistics_supply_chain.rename(new_cols_dict, axis=1, inplace=True)

In [21]:
# checking our dataframe to see if the mappings have worked
logistics_supply_chain.head()

,time,vehicle_gps_latitude,vehicle_gps_longitude,fuel_consumption_rate,eta_variation_hours,traffic_congestion_level,warehouse_inventory_level,loading_unloading_time,handling_equipment_availability,order_fulfillment_status,...,iot_temperature,cargo_condition_status,route_risk_level,customs_clearance_time,driver_behavior_score,fatigue_monitoring_score,disruption_likelihood_score,delay_probability,risk_classification,delivery_time_deviation
0,2021-01-01 00:00:00,40.375568,-77.014318,5.136512,4.998009,5.927586,985.716862,4.951392,0.481294,0.761166,...,0.574400,0.777263,1.182116,0.502006,0.033843,0.978599,0.506152,0.885291,Moderate Risk,9.110682
1,2021-01-01 01:00:00,33.507818,-117.036902,5.101512,0.984929,1.591992,396.700206,1.030379,0.620780,0.196594,...,-9.753493,0.091839,9.611988,0.966774,0.201725,0.918586,0.980784,0.544178,High Risk,8.175281
2,2021-01-01 02:00:00,30.020640,-75.269224,5.090803,4.972665,8.787765,832.408935,4.220229,0.810933,0.152742,...,-6.491034,0.253529,6.570431,0.945627,0.264045,0.394215,0.998633,0.803322,High Risk,1.283594
3,2021-01-01 03:00:00,36.649223,-70.190529,8.219558,3.095064,0.045257,0.573283,0.530186,0.008525,0.811885,...,-0.151276,0.877576,0.548952,4.674035,0.362885,0.905444,0.993320,0.025977,High Risk,9.304897
4,2021-01-01 04:00:00,30.001279,-70.012195,5.000075,3.216077,8.004851,914.925067,3.620890,0.020083,0.053659,...,2.429448,0.262081,8.861443,3.445429,0.016957,0.258702,0.912433,0.991122,High Risk,7.752484

In [22]:
# writing the final dataframe to an excel file that we will use in our Tableau visualisations. The file will be the 'london_bikes_final.xlsx' file and the sheet name is 'Data'
logistics_supply_chain.to_excel('logistics_supply_chain_final.xlsx', sheet_name='logistics_supply_chain_data')